apiVersion: apps/v1
kind: Deployment

metadata:
  name: jobportal
  namespace: jobportal

spec:

  replicas: 2

  selector:
    matchLabels:
      app: jobportal

  template:

    metadata:
      labels:
        app: jobportal

    spec:

      containers:

        - name: jobportal

          image: jobportal:1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:

            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/jobdb

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: jobportal-config
                  key: SPRING_PROFILES_ACTIVE

          resources:

            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:

            httpGet:
              path: /actuator/health/readiness
              port: 8080

            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:

            httpGet:
              path: /actuator/health/liveness
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 20